name: flutter_app_template
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

flutter_icons:
  ios: true
  android: true
  windows: true
  image_path: "assets/cbj_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/cbj_icon_adaptive.png"

flutter:
  # Ensures that the Material Icons font is included with your application.
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/

  fonts:
    - family: gidole_regular
      fonts:
        - asset: assets/gidole_regular.ttf

dependencies:
  # Declarative routing solution, where everything needed for navigation is automatically generated for you.
  auto_route: ^3.2.2
  # Automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0
  # Helps implement the BLoC pattern.
  bloc: ^8.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  # Functional programming thingies, let you use multiple return types
  # Functional programming thingipes, let you use multiple return types
  dartz: ^0.10.1
  # Internationalization (Easy translations)
  easy_localization: ^3.0.0

  flutter:
    sdk: flutter
  # Bloc for state management, replace StatefulWidget
  flutter_bloc: ^8.0.1
  # Toast Library for Flutter, Easily create toast messages in single line of code.
  fluttertoast: ^8.0.8
  # Font Awesome Icon pack available as Flutter Icons.
  font_awesome_flutter: ^9.2.0
  # Annotations for freezed
  freezed_annotation: ^1.1.0
  # Service locator
  get_it: ^7.2.0
  # Add hex color codes to your flutter projects
  hexcolor: ^2.0.6
  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.13.4
  # Convenient code generator for get_it
  injectable: ^1.5.3
  # Allow you to have a screen at launcher for example
  introduction_screen: ^2.1.0
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.4.0
  # Dart Build System builders for handling JSON.
  json_serializable: ^6.1.4
  # Port of Kotlin's Kotlin Standard library for Dart/Flutter projects
  kt_dart: ^0.10.0
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.1.0
  # The Material Design Icons designed by the community for Flutter
  material_design_icons_flutter: ^5.0.6595
  # Creating multi-select widgets in a variety of ways
  multi_select_flutter: ^4.0.0
  # Popup that ask for the requested permission
  permission_handler: ^8.3.0
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^6.0.2
  # Implementation of the popular reactiveX api for asynchronous programming
  rxdart: ^0.27.3
  # Plugin for launching a URL
  url_launcher: ^6.0.18


dev_dependencies:
  # Generator for auto_route library.
  auto_route_generator: ^3.2.1
  # A build system for Dart code generation and modular compilation.
  build_runner:

  # Package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  # Code generator for unions/pattern-matching/copy.
  freezed: ^1.1.1
  # Convenient code generator for get_it.
  injectable_generator: ^1.5.3
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^1.8.2
  # Mock framework with APIs for Fakes, Mocks, behavior verification, and stubbing.
  mockito: ^5.0.12